### ISSUE TITLE
The more data, the worse the effect，how to solve it

### ISSUE THREAD

**Issue by hitxiaowandou** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#17]
hi,I am recommend algorithmic workers.thank you for your work about poi recommend.when I train this code with more data,it get  Recall@5 = 0.18,but when I use part=128,it works well,recall@5 = 0.45. In some other issues,you say "If more users lead to lower accuracy, it could imply a challenge for personalization. We guess that the model capacity we used for reproduction is not large enough to accommodate so many users' personalization (different user has different embedding)",so I want to know do you have some method to solve this problem. I am looking forward to your reply,thanks

**Comment by yingtaoluo** [comment]
Thank you for asking. I have not tried yet to maintain the performance with more users, and I can only assume that since the model can predict the POIs of each proportion of users well, with a larger capacity it ideally can accommodate all users' modeling. All baselines are used with this "part" division trick in comparison in order to get similar results reported in previous papers. It is hard for us to get similar results reported too if using more users... unfortunately. There are similar issues pushed.
