### ISSUE TITLE
Where are the evaluation results of other methods reported in the paper from?

### ISSUE THREAD

**Issue by yeliudev** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#22]
Hi @yingtaoluo, may I ask that did you reproduce other methods (e.g. GeoSAN, LSTPM, etc.) on exactly the same datasets you used for STAN, or did you just copy the results from elsewhere? I notice that almost all the papers in POI recommendation use their own dataset pre-processing methods, and did not mention where are the results of other methods from. Thanks!

**Comment by yeliudev** [comment]
@yingtaoluo

**Comment by yingtaoluo** [comment]
Yes, it is indeed a problem. There are very few open source codes as well. Just hope some people may find it useful to build upon STAN's code (although awful & ugly, TBH) to write their own model, especially those that are starters in the area. We use the same preprocessing, since different preprocessing for different methods can be painfully time-costly.
