### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by bb67ao** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#23]
Very interested in your job,I see your work is compared with TISARS ,I don't konw whether your idea is come from that paper.No matter true or not ,have you ever do the test which just construct spatial-temporal affect in that model instead of make a new model.

**Comment by yingtaoluo** [comment]
Yes, the paper in question builds upon TISARS. While I wouldn't categorize it as a completely new model, STAN does effectively integrate previous concepts in a cohesive manner, potentially/hopefully offering insights. By deviating from conventional assumptions such as the POI area, it demonstrates a different perspective that distinguishes it from earlier approaches with strong assumptions. If one must ask me if STAN is trivial/marginal, I would say the reviewers were lenient, and we were extremely lucky. I would reject papers like STAN if I see it in 2023. It has been two years and many new techniques have emerged, so feel free to move on and try new things. :)

As it has been a while since this paper is out there, the focus of my own research interest also shifts a lot. I personally apologize for any delayed responses and have to apologize if there is no future maintenance for this repo... But there have been many interesting works since 2021, do not hesitate to look at some of those good works people have done. :) Good luck to you all.
