### ISSUE TITLE
关于数据

### ISSUE THREAD

**Issue by BigTaige** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#26]
作者您好，请问训练数据的time是怎么算出来的，将时间字符串转换成时间戳以后，还需要那些处理？谢谢！

**Comment by BigTaige** [comment]
我搞明白了，不好意思

**Comment by datacheff** [comment]
你好，请问你是怎么做到的？

**Comment by Yukayo** [comment]
老哥你整明白是什么意思了吗，是吧时间戳变成mktime后除60吗

**Comment by IMTJG** [comment]
求解答

**Comment by yingtaoluo** [comment]
Sorry for delayed response. The email notification has been turned off and the repo will have a very low maintenance, unfortunately. The time, if I recall it correctly, is set to 0 for the earliest time and then assign the difference to this earliest time for other times. The division is 60, since time units like “second” are too small/concise and can be noise.
