### ISSUE TITLE
Preprocessing code

### ISSUE THREAD

**Issue by hussienalbared** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#28]
Thanks you so much for sharing the code I am wondering if you could share the preprocessing code which you have applied on the raw dataset?

**Comment by yingtaoluo** [comment]
Thank you. The preprocessing codes are in the repo, although we transformed the .csv file to .npy and then preprocess on the .npy file. Thanks.

**Comment by yingtaoluo** [comment]
As it has been a while since this paper is out there, the focus of my own research interest also shifts a lot. I personally apologize for any delayed responses and have to apologize if there is no future maintenance for this repo... But there have been many interesting works since 2021, do not hesitate to look at some of those good works people have done. :) Good luck to you all.
